### ISSUE TITLE
[Bug] WSA Script using old version for builds

### ISSUE THREAD

**Issue by robbely** [YT-Advanced/WSA-Script#1032]
### Steps to reproduce

1. Run WSA Script (using online link)
2. Download completed build
3. Check version

### Expected behaviour

Build version should be "2311.40000.3.0" which is listed as the current stable build on the main page.

### Actual behaviour

After 2 attempts, both versions are build 2310.40000.2.0

### Windows version

10.0.19045.3693

### Build Issue number

1031

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
This is because you choose retail instead of latest

**Comment by robbely** [comment]
From the main page:
STABLE BUILDS: Follows the "WSA Retail Channel" current version: 2311.40000.3.0

There doesn't seem to be a "latest" option, only Retail, WSA Insider, Release Preview, Insider Slow and Insider Fast

Is the main page incorrect, and so should the 2311.40000.3.0 still only be listed under PRE-RELEASE?

**Comment by YT-Advanced** [comment]
> From the main page:
> STABLE BUILDS: Follows the "WSA Retail Channel" current version: 2311.40000.3.0
> 
> There doesn't seem to be a "latest" option, only Retail, WSA Insider, Release Preview, Insider Slow and Insider Fast
> 
> Is the main page incorrect, and so should the 2311.40000.3.0 still only be listed under PRE-RELEASE?

Ah seem like our mistake

**Comment by robbely** [comment]
> Ah seem like our mistake

Which was the mistake, the version number on the main page or the one being used for creating release builds?

**Comment by YT-Advanced** [comment]
> > Ah seem like our mistake
> 
> Which was the mistake, the version number on the main page or the one being used for creating release builds?
> 
The version number on the main page is incorrect bro

**Comment by robbely** [comment]
> The version number on the main page is incorrect bro

I see you've corrected it now, however I think you got it the wrong way round as you now have the pre-release build as the older (2310) one and the stable build as the newer (2311) one.
