### ISSUE TITLE
How to Install VpnDialogs https://github.com/LSPosed/VpnDialogs

### ISSUE THREAD

**Issue by SonaliBendre** [YT-Advanced/WSA-Script#109]
https://github.com/LSPosed/VpnDialogs

**Comment by YT-Advanced** [comment]
@SonaliBendre I think you should ask @s1204IT

**Comment by s1204IT** [comment]
Optionally create another item to install.

**Comment by s1204IT** [comment]
> @s1204IT But the app didn't work. So install have no effect

Yes, it do.
