### ISSUE TITLE
[Bug] Anyone know how to fix the install failing?

### ISSUE THREAD

**Issue by WWIA7062** [YT-Advanced/WSA-Script#1115]
### Steps to reproduce

1. run tge djgnosite in the tutorial
2. get the error 
3. Not knowing how to fix
4. 4. Askinf for hekp

### Expected behaviour

It sjould inatall but idk how to fix it. Plz help (maybe even before 2024 XD)

### Actual behaviour

Time                      ID           Message
----                      --           -------
12/31/2023 11:49:19 PM    603          Started deployment Register operation on a package with main parameter AppxManifest.xml and Options
                                       ForceApplicationShutdownOption,DevelopmentModeOption,ForceUpdateFromAnyVersion and 0. See
                                       http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
12/31/2023 11:49:19 PM    216          App manifest validation warning: Declared namespace http://schemas.microsoft.com/developer/appx/2015/build is
                                       inapplicable, it will be ignored during manifest processing.
12/31/2023 11:49:19 PM    709          Rejecting a request to register from AppxBundleManifest.xml because the manifest is not in the package root.
12/31/2023 11:49:19 PM    404          AppX Deployment operation failed for package  with error 0x80070057. The specific error text for this failure is:
                                       Rejecting a request to register from AppxBundleManifest.xml because the manifest is not in the package root.

### Windows version

11 232H

### Build Issue number

#1113 

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by WWIA7062** [comment]
also i have an update, its still groken but the erroe code was in the common errors however the message was not the same from thepage and I did the instructions from the bug page 2 times and I have the same error as bwfofe. (legion go on screen kehborad be bad tbh sp sorry for typos)
![Screenshot 2024-01-01 031354](https://github.com/YT-Advanced/WSA-Script/assets/90222465/5112d864-7c6d-455f-a3fe-7110a0367020)
![WSA custom build info](https://github.com/YT-Advanced/WSA-Script/assets/90222465/40b6f44b-207d-4052-aec7-c6c589f00e96)
![WSA custom build install error](https://github.com/YT-Advanced/WSA-Script/assets/90222465/57715446-b931-4bf6-bd1c-f55ee5effb18)

**Comment by WWIA7062** [comment]
also didnt mean to close it

**Comment by WWIA7062** [comment]
IDK how to fix it still but yeah I'm gonna keep trying but if anyone knows how to fix it plz let me know

**Comment by WWIA7062** [comment]
(and my spelling sucked since i was using the windows 11 on screen keyboard on my legion go.)

**Comment by rovarp** [comment]
same problem

**Comment by s1204IT** [comment]
Once you have **completely** removed WSA, download the latest version and try it from **`Run.bat`**.
