### ISSUE TITLE
[Feature Request] Change Device Model

### ISSUE THREAD

**Issue by ARDEACT** [YT-Advanced/WSA-Script#1184]
### Is your feature request related to a problem?

I want the ability to change the Device model as some apps are not compatible with Pixel 5.
I've tried:
1. Installing Busybox + Props modules but I couldn't get Busybox to work ($PATH is linked incorrectly when installing Busybox and I have no clue on how to fix it so that the Props module detects Busybox)
2. Editing the build.prop directly with a file editor but no matter how many permissions I grant it with KernelSU, I cannot get it to save.
3. Tried ADB pushing a modified build.prop but ADB comes up with "ADB root cannot be used with production versions".
Overall, I'm very tired and frustrated I couldn't get it to work. 

### Describe the solution you'd like

I'm not sure how to effectively change the Device model, I'm up to any solution since I've tried many.

**Comment by BraINstinct0** [comment]
You can manually create an issue (see [the folded part](https://github.com/YT-Advanced/WSA-Script#--want-to-build-your-custom-build-) that builds with the selected device model.

**Comment by s1204IT** [comment]
Not only WSA, but all terminals where dm-verity exists cannot write to the system area even if they have root privileges.

Basically, perform [Custom Build](https://yt-advanced.github.io/WSA-Script/) again.

If it is really a hassle, please change it by creating a Magisk or KernelSU module.

Also, `adb root` cannot be used if the Android build variant is `release` even if root privileges can be obtained.
