### ISSUE TITLE
[Bug] Will not work unless Windows login is adminstrator

### ISSUE THREAD

**Issue by Rosie202402** [YT-Advanced/WSA-Script#1296]
### Steps to reproduce

1. Ran run.bat as administrator.  Did not work.
2. Ran the ps1 file as an administrator.  Did not work.
3. Signed off, signed back in on admin login, gave user login admin privileges, signed out as admin and in as user.
4. Run.bat worked!  :-)
5. Very happy now but it took me two days to figure this out.  You could've maybe just said in the installation instructions when you were describing what to do if run.bat doesn't work?

### Expected behaviour

Installation instructions include all common reasons why run.bat and ps1 file might not work.

### Actual behaviour

Based on the current installation instructions, I was convinced that the computer simply would not support WSA, possibly because we're in Canada.  Except then I tried it on another computer bought in the same batch of computers where the user login already had admin privileges and everything worked fine there.

You're probably laughing at me, but I'm the de facto IT person for a small charity.  I may not be much, but I'm the best we've got.

### Windows version

Version 22H2 Windows 11

### Build Issue number

22621.3155

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by s1204IT** [comment]
Basically, that's normal.
This project is not writing a script to explain how to operate Windows, so I'm sorry, but I'll ignore it.
