### ISSUE TITLE
Custom WSA Build for testing

### ISSUE THREAD

**Issue by YT-Advanced** [YT-Advanced/WSA-Script#13]
--arch x64 --release-type WIF --magisk-ver delta --gapps-brand MindTheGapps --gapps-variant pico --root-sol magisk --compress-format xz --remove-amazon

**Comment by YT-Advanced** [comment]
> @YT-Advanced 你好，我在构建WSA时发现【User code for WSA Insider User (Optional)】可选参数，请问这个参数是什么？按照我的理解，填入此参数后会从WSA的预览计划中获取下载地址？我是预览计划成员，请问User code指的是什么？

@callng 这是由创建的功能 @s1204IT  所以我真的不知道它是如何工作的

**Comment by s1204IT** [comment]
https://github.com/LSPosed/MagiskOnWSALocal/commit/615c125
https://github.com/LSPosed/MagiskOnWSALocal/issues/282#issuecomment-1352572007
https://github.com/LSPosed/MagiskOnWSALocal/issues/279#issuecomment-1356127376


https://github.com/LSPosed/MagiskOnWSALocal/discussions/298#discussioncomment-4441911
/

**Comment by s1204IT** [comment]
This feature does not always make sense.
