### ISSUE TITLE
[Feature Request] APatch support

### ISSUE THREAD

**Issue by anaelle-dev** [YT-Advanced/WSA-Script#1310]
### Is your feature request related to a problem?

Please add support for APatch
https://github.com/bmax121/APatch

### Describe the solution you'd like

I would like to suggest the addition of support for APatch, a root solution similar to Magisk and KernelSU, to WSA Script.

**Comment by s1204IT** [comment]
Since none of the owner/collaborators of this project have an arm64 device, which means we are unable to verify its operation, we will close this proposal.
