### ISSUE TITLE
[Bug] Error build

### ISSUE THREAD

**Issue by LordArrin** [YT-Advanced/WSA-Script#1359]
### Steps to reproduce

Generating KernelSU download link: arch=x86_64, kernel version=5.15.104.4
Error: No KernelSU Manager release found
Build: an error has occurred, exit
Error: Process completed with exit code 1.

### Expected behaviour

succesful build

### Actual behaviour

error

### Windows version

26052.1100

### Build Issue number

#2176

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
Fixed right now xD
