### ISSUE TITLE
[Bug] Microsoft Defender detects vendor.vhdx as Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by RoonMoonlight** [YT-Advanced/WSA-Script#1398]
### Steps to reproduce

1. Install the zip file (It was WSA_2311.40000.5.0_x64_Release-Nightly-NoGApps-as-Pixel-5-RemovedAmazon.7z)
2. Unzip it
3. Microsoft Defender detects vendor.vhdx as Wacatac

### Expected behaviour

It should not detect as virus

### Actual behaviour

It detected as virus

### Windows version

10.0.22631.3296

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by s1204IT** [comment]
Please check Windows Update and try again.
