### ISSUE TITLE
[Feature Request] Model change.

### ISSUE THREAD

**Issue by rafaalbino** [YT-Advanced/WSA-Script#1410]
### Is your feature request related to a problem?

Some applications are not supported in the store, even on Aurora. An example is Genshin, which on the other hand has the Honkai Star Rail available. As I don't know if it's a limitation, I came to ask

### Describe the solution you'd like

If possible, make the system compatible or explain this limitation in the FAQ or tutorial.

**Comment by s1204IT** [comment]
Unfortunately, that problem is not something that this project can solve.

At least, I was adding custom models as I tweaked them, but LSPosed killed that functionality.
