### ISSUE TITLE
Magisk Delta link not working so reverts to TopJohnWu Magisk

### ISSUE THREAD

**Issue by Longjohn1** [YT-Advanced/WSA-Script#1480]
### Steps to reproduce

1. Choose huskydog version of magisk in custom build
2. Reverts to topjohnwu version when building
3. I think huskeydog link needs updating
4. 

### Expected behaviour

Build with magisk delta

### Actual behaviour

Build with topjohnwu magisk

### Windows version

?

### Build Issue number

?

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
Thanks, I solved this bug
