### ISSUE TITLE
[Bug] Short description.

### ISSUE THREAD

**Issue by wyr121** [YT-Advanced/WSA-Script#1518]
### Steps to reproduce

1. 下载
2. 解压
3. 运行

### Expected behaviour

安装成功

### Actual behaviour

安装失败
![image](https://github.com/YT-Advanced/WSA-Script/assets/72083417/49ceb686-bd09-4d2e-8f4c-2acf320bc3f5)

### Windows version

22631.3593

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
Duplicate with https://github.com/YT-Advanced/WSA-Script/issues/1199
