### ISSUE TITLE
[SECURITY VULNERABILITY] In your codebase is a reference of the cdn com polyfill com io service

### ISSUE THREAD

**Issue by PriNova** [YT-Advanced/WSA-Script#1541]
https://github.com/YT-Advanced/WSA-Script/blob/24b45ef9fc6deea4a9ab62f6d184aa023346f7ba/docs/Issues.html#L48

This file is using the cdn.polyfill.io service which is known for injecting malicious code

Please use the cloudflare polyfill service

https://x.com/WeldPond/status/1805973940642119900

**Comment by YT-Advanced** [comment]
@PriNova rn I am extremly busy, can you open PRs. Thanks a lot !
