### ISSUE TITLE
[Bug] Missing file from filelist.txt

### ISSUE THREAD

**Issue by acestars** [YT-Advanced/WSA-Script#1597]
### Steps to reproduce

1. Create any custom build
2. Download and extract the file
3. Execute Run.bat

### Expected behaviour

Installed successfully

### Actual behaviour

Error occurred
Some files are missing in the folder.
Please try to build again.
Press any key to exit

The missing files are:
pri
xml
MakePri.ps1

The solution:
Open filelist.txt and remove the missing items.

### Windows version

Windows 11 Pro 23H2 22631.3880

### Build Issue number

#1593

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
Can you recheck, thanks

**Comment by acestars** [comment]
`pri
xml`
Still exists in filelist.txt
