### ISSUE TITLE
[Bug] `apex` folder got removed when choose 7zip as compression method

### ISSUE THREAD

**Issue by julerobb1** [YT-Advanced/WSA-Script#1613]
### Steps to reproduce

1. download any version of the 7z files, magisk, kenrl su, non root versions
2. run the run .bat or powershell script
3. ALL FAIL WITH MISSING FILES

how about making something that acutally works insted of me wasting my time attempting to get this working. This was time spent ill never get back. 

### Expected behaviour

Should install fine, and launch and be rooted

### Actual behaviour

Doesnt do any of the abvoe just fails. Even after doing all the troubleshooting steps. 7Zip is not the issue. Its a case of the Dev making something that does not work on every machine. 
![image](https://github.com/user-attachments/assets/09aada26-a8b0-492d-b90b-e92a743348af)

### Windows version

22631.3880

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
How about Custom Build ?

**Comment by AccountCrack** [comment]
Use this file
[filelist.txt](https://github.com/user-attachments/files/16400643/filelist.txt)

**Comment by stanleyyeung** [comment]
I'm coming across the same issue with WSA_2311.40000.5.0_arm64_Release-Nightly-GApps-13.0-NoAmazon on a Windows 11 Insider Build.  I also tried the WsaSetup.exe in the Custom Build folder and checked the filelist.txt.  It seems I'm missing the apex folder.

**Comment by YT-Advanced** [comment]
> I'm coming across the same issue with WSA_2311.40000.5.0_arm64_Release-Nightly-GApps-13.0-NoAmazon on a Windows 11 Insider Build.  I also tried the WsaSetup.exe in the Custom Build folder and checked the filelist.txt.  It seems I'm missing the apex folder.

Thanks for your information. Can you create an empty apex folder before installing

**Comment by TriDefender** [comment]
> > I'm coming across the same issue with WSA_2311.40000.5.0_arm64_Release-Nightly-GApps-13.0-NoAmazon on a Windows 11 Insider Build.  I also tried the WsaSetup.exe in the Custom Build folder and checked the filelist.txt.  It seems I'm missing the apex folder.
> 
> Thanks for your information. Can you create an empty apex folder before installing

I think it misses more than just apex, however the installation was successfull if I removed the filecheck process

**Comment by stanleyyeung** [comment]
It finally installs.  But unfortunately the Google Play Store still doesn't show up on my Start menu after the WSA finishes loading...

**Comment by YT-Advanced** [comment]
> It finally installs. But unfortunately the Google Play Store still doesn't show up on my Start menu after the WSA finishes loading...

You should wait some minute for the initialize of Play Store and other app

**Comment by stanleyyeung** [comment]
Yes it does load longer this time than usual.  But there is still no Google Play Store in my Start menu after it is done and I also cannot connect to the adb at 127.0.0.1:58526.

**Comment by YT-Advanced** [comment]
Should be fixed with hot fix in [the latest releases](https://github.com/YT-Advanced/WSA-Script/releases/tag/v2024-07-28)

Make sure that you have uninstall your current WSA
