### ISSUE TITLE
[Bug] WSA_2407.40000.0.0_x64_Release-Nightly-GApps-13.0-NoAmazon.7z with MAGISK

### ISSUE THREAD

**Issue by kozseb** [YT-Advanced/WSA-Script#1619]
### Steps to reproduce

WSA_2407.40000.0.0_x64_Release-Nightly-GApps-13.0-NoAmazon.7z with MAGISK

### Expected behaviour

New pack

### Actual behaviour

magisk

### Windows version

2407.40000.0.0

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
Since GApps need external file from Magisk to be integrated, so Magisk will be installed when you choose GApps
