### ISSUE TITLE
[Bug] KSU with Gapps result incorrect root vendor

### ISSUE THREAD

**Issue by TriDefender** [YT-Advanced/WSA-Script#1620]
### Steps to reproduce

1. Download and install https://github.com/YT-Advanced/WSA-Script/releases/download/v2024-07-28/WSA_2311.40000.5.0_x64_Release-Nightly-with-kernelsu-v1.0.1-GApps-13.0-NoAmazon.7z
2. 
3. 

### Expected behaviour

It's supposed to be packed with kernelsu

### Actual behaviour

It's packed with magisk
![image](https://github.com/user-attachments/assets/c78ff3ce-487e-416a-8ea9-b89960e1e0f4)

### Windows version

23h2

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
Duplicate with #1619

For short, due to the limitation of our implementation, Magisk is needed for integrate GApps

**Comment by YT-Advanced** [comment]
However, I will try to fix this issues 👀

**Comment by YT-Advanced** [comment]
Hi there @TriDefender, I have fixed your issues, can u check this build xD
https://github.com/YT-Advanced/WSA-Script/actions/runs/10177722181
