### ISSUE TITLE
[Bug] Short description. release file have an error name  and with magisk one have two startup programe

### ISSUE THREAD

**Issue by Alfred1109** [YT-Advanced/WSA-Script#1683]
### Steps to reproduce

1.  the prerelease and stable release are both wrong on name ,such as nongapp are bigger then gapp.
2. and when I run the wsa with magisk there are two startupprogrames
3. and when I run the wsa  with other edition vpn can not work well.

### Expected behaviour

can you resolve the problem up?

### Actual behaviour

I have tried so many times

### Windows version

windows 11 26100.1742

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
> The prerelease and stable release are both wrong on name ,such as nongapp are bigger then gapp.

This is normal behavior, since we use different method for magisk and non-magisk build

> When I run the wsa with magisk there are two startupprogrames

Yea, the script will automatically open the Magisk and Gapps, so that's the reason that there are 2 startup program

> When I run the wsa with other edition vpn can not work well.

Microsoft disabled VPN
