### ISSUE TITLE
Custom WSA Build Do not edit this

### ISSUE THREAD

**Issue by pavan3999** [YT-Advanced/WSA-Script#1687]
--arch x64 --release-type retail --root-sol none --magisk-branch topjohnwu --magisk-ver stable --custom-model tangorpro --compress-format 7z --install-gapps --remove-amazon

**Comment by pavan3999** [comment]
custom model removed??

**Comment by YT-Advanced** [comment]
> custom model removed??

uhm yea, we removed it 🫠
