### ISSUE TITLE
WSA_2407.40000.0.0_x64_Release-Nightly-Gapps-13.0-NoAmazon does not contain Gapps

### ISSUE THREAD

**Issue by jparnell8839** [YT-Advanced/WSA-Script#1718]
### Steps to reproduce

1. Download latest build of WSA_2407.40000.0.0_x64_Release-Nightly-Gapps-13.0-NoAmazon
2. Install via Run.bat, receive successful WSA installation
3. Start WSA

### Expected behaviour

Google Play Store is installed

### Actual behaviour

No Google Play Store is installed

### Windows version

26100.1742

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by Eisaichen** [comment]
The Gapps version and non-Gapps version have been swapped by mistake.

**Comment by YT-Advanced** [comment]
Fixed with https://github.com/YT-Advanced/WSA-Script/pull/1824
