### ISSUE TITLE
[Bug] Not working with the new Magisk v28

### ISSUE THREAD

**Issue by Wizards-god** [YT-Advanced/WSA-Script#1731]
### Steps to reproduce

1. Choose Magisk as root solution
2. Choose Magisk beta as channel
3. Run workflow

### Expected behaviour

The workflow should run and give me an output.

### Actual behaviour

The workflow runs into an error while downloading magisk.
I suspect this is because the download link format for Magisk v28 has changed from 'https://github.com/topjohnwu/Magisk/releases/download/v28.0/Magisk-v28.0.apk' [This is what the workflow expects] -- to 'https://github.com/topjohnwu/Magisk/releases/download/v28.0/app-release.apk'.
Would appreciate it if this gets fixed😊.

### Windows version

22635.4300

### Build Issue number

#1730

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
Can u recheck again xD
