### ISSUE TITLE
[Bug] Can't install kernalSU.

### ISSUE THREAD

**Issue by XieAofan** [YT-Advanced/WSA-Script#1733]
### Steps to reproduce

adb shell ksuinstall

### Expected behaviour

adb shell ksuinstall

### Actual behaviour

![屏幕截图 2024-10-16 113052](https://github.com/user-attachments/assets/52cc5bd4-9045-4535-9e8c-93c1eca4baa7)

### Windows version

win11 23H2

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by ilbebino08** [comment]
same issue here

**Comment by YT-Advanced** [comment]
Wwe removed the ksuinstall script. Right now, u have to install manager manually
