### ISSUE TITLE
[Bug] Missing files

### ISSUE THREAD

**Issue by IAemPerse6** [YT-Advanced/WSA-Script#1771]
### Steps to reproduce

1. run bat
2. *missing files
3. 

### Expected behaviour

success

### Actual behaviour

*missing files

so can u pls check all files before uploading updates.

### Windows version

22635.4440

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by likertuban** [comment]
open filelist.txt
then remove this line, and save and run run.bat again :
apex
apex\\.gitkeep
