### ISSUE TITLE
[Bug] Some files are missing in the folder

### ISSUE THREAD

**Issue by crea1110** [YT-Advanced/WSA-Script#1775]
### Steps to reproduce

1. Run the Install.ps1 file using PowerShell

### Expected behaviour

Start the installation normally

### Actual behaviour

An error occurred, prompting Some files are missing in the folder.
After checking filelist.txt, I found that the APEX folder was missing.
![Some files are missing in the folder](https://github.com/user-attachments/assets/492f9531-2fc4-4b0d-8669-b2e454931cfc)

### Windows version

win11 24H2

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
Uhm can u remove apex word in filelist.txt and recheck

**Comment by crea1110** [comment]
After removing it, new problems appeared
![20241112121355](https://github.com/user-attachments/assets/7765585d-085f-4259-bd38-11fd0d97e392)

**Comment by YT-Advanced** [comment]
> After removing it, new problems appeared
> ![20241112121355](https://github.com/user-attachments/assets/7765585d-085f-4259-bd38-11fd0d97e392)
> 

Press y letter to continue the installation

**Comment by crea1110** [comment]
Thanks for your answer, it has been successfully installed, but there is no Google service

**Comment by YT-Advanced** [comment]
> Thanks for your answer, it has been successfully installed, but there is no Google service

Uhm it may need some minute from the first start to install

**Comment by crea1110** [comment]
I waited for dozens of minutes and Google still didn't show up on my computer

**Comment by YT-Advanced** [comment]
Uhm which file that you have downloaded

**Comment by crea1110** [comment]
WSA_2407.40000.0.0_x64_Release-Nightly-Gapps-13.0-NoAmazon.7z

**Comment by YT-Advanced** [comment]
> WSA_2407.40000.0.0_x64_Release-Nightly-Gapps-13.0-NoAmazon.7z

Uhm can u check with magisk version

**Comment by YT-Advanced** [comment]
> Uninstall the current version and then install the magisk version?

yea, right

**Comment by crea1110** [comment]
Now it is installed normally，Thanks for your answers！

**Comment by likertuban** [comment]
open filelist.txt
then remove this line, and save and run run.bat again :
apex
apex\\.gitkeep
