### ISSUE TITLE
Some Files are missing in the folder

### ISSUE THREAD

**Issue by aiknayan** [YT-Advanced/WSA-Script#1813]
### Steps to reproduce

1. Installed [KB5014032](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5014032) & [KB5022834](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5022834)
2. Double click Run.bat 

### Expected behaviour

WSA Installation

### Actual behaviour

Gives below attached missing files error. I tried both [WSA_2407.40000.4.0_arm64_Release-Nightly-Gapps-13.0-NoAmazon.7z](https://github.com/YT-Advanced/WSA-Script/releases/download/v2024-12-19/WSA_2407.40000.4.0_arm64_Release-Nightly-Gapps-13.0-NoAmazon.7z), [WSA_2407.40000.4.0_x64_Release-Nightly-with-magisk-28.1.28100.-stable-GApps-13.0-NoAmazon.7z](https://github.com/YT-Advanced/WSA-Script/releases/download/v2024-12-19/WSA_2407.40000.4.0_x64_Release-Nightly-with-magisk-28.1.28100.-stable-GApps-13.0-NoAmazon.7z)

![IMG_6200](https://github.com/user-attachments/assets/63318d9d-ecf6-4a4b-8e40-dabda24031c2)

### Windows version

Windows 10 21H2 (OS Build 19044.2604)

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
Can u open filelist.txt and check one by one

**Comment by aiknayan** [comment]
What I have to check in filelist.txt?

**Comment by Ognisty321** [comment]
@YT-Advanced Can you make a release with all the files?

**Comment by likertuban** [comment]
open filelist.txt
then remove this line, and save and run run.bat again :
apex
apex\.gitkeep

**Comment by YT-Advanced** [comment]
Uhm is apex folder appear in extracted folder

**Comment by likertuban** [comment]
> Uhm is apex folder appear in extracted folder

it's not appear in the extracted zip, but appear in filelist.txt, that is why the installation fail, since the folder apex only contain .gitkeep, removing it from the filelist.txt or create an empty file/folder with the same name should have worked too

**Comment by YT-Advanced** [comment]
Should be fixed in latest releases
