### ISSUE TITLE
GApps not installing

### ISSUE THREAD

**Issue by eliekh05** [YT-Advanced/WSA-Script#26]
when running run.bat gapps are not installing only windows subsystem for android settings installed but i have WSA_2303.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon

**Comment by YT-Advanced** [comment]
> when running run.bat gapps are not installing only windows subsystem for android settings installed but i have WSA_2303.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon

Your build you have downloaded don't have Gapps. Use WSA_2303.40000.5.0_x64_Release-Nightly-with-magisk-26.1(26100)-stable-MindTheGapps-13.0-RemovedAmazon.7z from the latest instead

**Comment by eliekh05** [comment]
> > when running run.bat gapps are not installing only windows subsystem for android settings installed but i have WSA_2303.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon
> 
> 
> 
> Your build you have downloaded don't have Gapps. Use WSA_2303.40000.5.0_x64_Release-Nightly-with-magisk-26.1(26100)-stable-MindTheGapps-13.0-RemovedAmazon.7z from the latest instead

but before when i first time downloaded the file that i mentioned and opened run.bat file it opened google play store

**Comment by YT-Advanced** [comment]
> > > when running run.bat gapps are not installing only windows subsystem for android settings installed but i have WSA_2303.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon
> > 
> > 
> > 
> > Your build you have downloaded don't have Gapps. Use WSA_2303.40000.5.0_x64_Release-Nightly-with-magisk-26.1(26100)-stable-MindTheGapps-13.0-RemovedAmazon.7z from the latest instead
> 
> but before when i first time downloaded the file that i mentioned and opened run.bat file it opened google play store 

Can you edit your problem with fluently English. I cannot understand what do u mean

**Comment by eliekh05** [comment]
> > > > when running run.bat gapps are not installing only windows subsystem for android settings installed but i have WSA_2303.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon
> > > 
> > > 
> > > 
> > > Your build you have downloaded don't have Gapps. Use WSA_2303.40000.5.0_x64_Release-Nightly-with-magisk-26.1(26100)-stable-MindTheGapps-13.0-RemovedAmazon.7z from the latest instead
> > 
> > but before when i first time downloaded the file that i mentioned and opened run.bat file it opened google play store 
> 
> Can you edit your problem with fluently English. I cannot understand what do u mean

before when i first downloaded and extracted and ran the run.bat file and when finished the file opened google play store

**Comment by YT-Advanced** [comment]
> before when i first downloaded and extracted and ran the run.bat file and when finished the file opened google play store

And how about now ?

**Comment by eliekh05** [comment]
> > before when i first downloaded and extracted and ran the run.bat file and when finished the file opened google play store
> 
> And how about now ?

now trying WSA_2303.40000.5.0_x64_Release-Nightly-with-magisk-26.1(26100)-stable-MindTheGapps-13.0-RemovedAmazon.7z after download

**Comment by eliekh05** [comment]
> > > before when i first downloaded and extracted and ran the run.bat file and when finished the file opened google play store
> > 
> > 
> > And how about now ?
> 
> now trying WSA_2303.40000.5.0_x64_Release-Nightly-with-magisk-26.1(26100)-stable-MindTheGapps-13.0-RemovedAmazon.7z after download

same thing if you can release an update WSA_2304.40000.5.0_x64_Release-Nightly-with-magisk-26.1(26100)-stable-MindTheGapps-13.0-RemovedAmazon.7z for fix

**Comment by MustardChef** [comment]
> 

Use the builds from here: https://github.com/MustardChef/WSABuilds

**Comment by MustardChef** [comment]
> > @eliekh05 Use the builds from here: https://github.com/MustardChef/WSABuilds
> 
> which one should i choose if i want google play

Do you want Magisk as well?

**Comment by eliekh05** [comment]
> > > @eliekh05 Use the builds from here: https://github.com/MustardChef/WSABuilds
> 
> > 
> 
> > which one should i choose if i want google play
> 
> 
> 
> Do you want Magisk as well?

only google

**Comment by MustardChef** [comment]
> > > > @eliekh05 Use the builds from here: https://github.com/MustardChef/WSABuilds
> > 
> > 
> > > 
> > 
> > 
> > > which one should i choose if i want google play
> > 
> > 
> > Do you want Magisk as well?
> 
> only google

It will be the first one

**Comment by YT-Advanced** [comment]
@eliekh05 If you need only google download this ones:
[x64](https://github.com/YT-Advanced/WSA-Script/releases/download/v2023-05-10/WSA_2303.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z)
[ARM64](https://github.com/YT-Advanced/WSA-Script/releases/download/v2023-05-10/WSA_2303.40000.5.0_arm64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z)

**Comment by YT-Advanced** [comment]
@eliekh05 Sorry if it annoyed you because of my testing
