### ISSUE TITLE
Custom WSA Build 180523

### ISSUE THREAD

**Issue by forconxo** [YT-Advanced/WSA-Script#30]
--arch x64 --release-type RP --magisk-ver stable --gapps-brand MindTheGapps --root-sol magisk --compress-format 7z --remove-amazon

**Comment by YT-Advanced** [comment]
@forconxo Sorry but my Github now didn't support build for WSA v2304. Waiting for this pull request merged then rebuild again. Thanks!
https://github.com/actions/runner-images/pull/7610

**Comment by YT-Advanced** [comment]
@forconxo Now I'm here to said that the repos now supported WSA v2304
