### ISSUE TITLE
[Feature Request] Please add Pixel XL (marlin) as an option for custom model

### ISSUE THREAD

**Issue by shivanshvermak** [YT-Advanced/WSA-Script#356]
### Is your feature request related to a problem?

Nope.

### Describe the solution you'd like

Hi, thanks for this script. Can you please add `marlin` (Pixel XL) as one of the custom models? Thank you!

**Comment by YT-Advanced** [comment]
@shivanshvermak Pixel XL is too old so it is not compatiable with current WSA Android
