### ISSUE TITLE
[Feature Request] Readme should include Current WSA versions for each channel.

### ISSUE THREAD

**Issue by BraINstinct0** [YT-Advanced/WSA-Script#438]
### Is your feature request related to a problem?

Current Readme does not reflect the updated WSA versions, although they are already built and on the server.
Also, for those who do not know which channel they are on, it can be confusing to choose which channel for build commands.

### Describe the solution you'd like

Add a table showing each versions for each channel

**Comment by YT-Advanced** [comment]
I can't understand what are you mentioning, can u explain more ?

**Comment by s1204IT** [comment]
@BraINstinct0 Was the problem resolved?

**Comment by BraINstinct0** [comment]
Well... partially.
My WSA (official) was 2307.40000.6.0, so I was not sure where I got it from. Back then the readme showed WSA version (latest) as 2307.40000.5.0, so I was kinda confused.
Seems that the Readme was edited soon after.... my bad.

However there's another issue - [The script site](https://yt-advanced.github.io/WSA-Script/Issues.html) shows release types as `retail`, `latest`, `RP` - Release Preview, `WIS` - Now called Beta, and `WIF` - Now called Dev.
Only two of those are shown in the Readme, so it's hard to figure out which channel to use if you forgot which category you fall into.

Someone might argue, "If you forget which channel you're in, that means you probably shouldn't use custom builds" - yes, yes, but it happens.

**Comment by BraINstinct0** [comment]
Besides if possible, editing the site to mention "Mouse over to see further details" would help.

**Comment by BraINstinct0** [comment]
Confirming the recent cleanup has fixed (and revived the missing-win11-terminology) most issues.
