### ISSUE TITLE
a problem with the browser page

### ISSUE THREAD

**Issue by hunanflyer** [YT-Advanced/WSA-Script#519]
### Steps to reproduce

1. 
2. 
3. 

### Actual behaviour

There is a problem with the browser page. All browsers cannot connect to the Internet, but GOOGLE PAYER can connect to the Internet.

### Version requirement

- [X] I am using latest commit of MagiskOnWSALocal commit

### Logs

<details>

```
# Replace this line with the log
```
</details>

**Comment by YT-Advanced** [comment]
Any screenshot ?

**Comment by s1204IT** [comment]
Duplicate #523
