### ISSUE TITLE
[Feature Request] Can I add google pixel xl 2016? Can I use Google Photos?

### ISSUE THREAD

**Issue by wyr121** [YT-Advanced/WSA-Script#530]
### Is your feature request related to a problem?

Can I add google pixel xl 2016? Can I use Google Photos?

### Describe the solution you'd like

Can I add google pixel xl 2016? Can I use Google Photos?

**Comment by s1204IT** [comment]
Thans for your request.

Thank you very much for your kind offer, but we will not accept the addition of "Google Pixel XL (marlin)".　　
The custom devices in this repository are not added at random, but based on official builds.  
"Google Pixel XL" does not support Android 13 (TQ3A), which may cause incorrect behavior as a device disguise.

Also, regarding Google Photos, are you talking about unlimited backup storage?
If that is the case, this repository cannot support it.
