### ISSUE TITLE
[Bug] localhost loopback instructions no longer working

### ISSUE THREAD

**Issue by pantherale0** [YT-Advanced/WSA-Script#559]
### Steps to reproduce

1. Install WSA following instructions in readme
2. Follow instructions to enable localhost loopback here: https://github.com/YT-Advanced/WSA-Script/blob/main/docs/Guides/LocalHostLoopback.md
3. Error in console

It appears that there are a few comments here relating to this https://github.com/microsoft/WSA/issues/213 so perhaps worth updating the guide itself?

### Expected behaviour

Commands should execute successfully

### Actual behaviour

```
Set-NetFirewallHyperVVMSetting : No MSFT_NetFirewallHyperVVMSetting objects found with property 'Name' equal to
'{9E288F02-CE00-4D9E-BE2B-14CE463B0298}'.  Verify the value of the property and retry.
At line:1 char:1
+ Set-NetFirewallHyperVVMSetting -VMCreatorId '{9E288F02-CE00-4D9E-BE2B ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ({9E288F02-CE00-4D9E-BE2B-14CE463B0298}:String) [Set-NetFirewallHyperVVM
   Setting], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_Name,Set-NetFirewallHyperVVMSetting
```

```
New-NetFirewallHyperVRule : The port is invalid.  When Protocol is TCP or UDP, individual ports or ranges are allowed.
 Also, the following port keywords are allowed on Firewall Rules: RPC, RPCEPMap, Teredo, IPHTTPSIn, IPHTTPSOut,
PlayToDiscovery.
At line:1 char:1
+ New-NetFirewallHyperVRule -DisplayName LoopbackAllow -VMCreatorId '{9 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (MSFT_NetFirewallHyperVRule:root/standardci...ewallHyperVRule) [New-Net
   FirewallHyperVRule], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070057,New-NetFirewallHyperVRule
```

### Windows version

22621.2283

### Build Issue number

Latest, unable to find number in action history

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by MustardChef** [comment]
@pantherale0 Localhost Loopback has now been officially added to the 2308 update of WSA, and so the guide is probably outdated now.

**Comment by YT-Advanced** [comment]
@MustardChef I am very busy right now, so can you make a Pull Request to update all the docs. Thank u

**Comment by YT-Advanced** [comment]
Updated
