### ISSUE TITLE
[Bug] Write-Error: Some files are missing since the last few releases

### ISSUE THREAD

**Issue by rp1231** [YT-Advanced/WSA-Script#566]
### Steps to reproduce

1. Extract the archive 
2. Run the run.bat file

### Expected behaviour

Should install WSA 

### Actual behaviour

This error occurs:
<img width="234" alt="pwsh_87pW47YwAs" src="https://github.com/YT-Advanced/WSA-Script/assets/47380919/78fd6b2e-4a3e-4398-b9b4-b36c65447e5f">

### Windows version

win 11 22H2

### Build Issue number

2308.40000.3.0

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by s1204IT** [comment]
Please try build again [**here**](https://yt-advanced.github.io/WSA-Script/Issues.html).  
If expand fail, files may be missing.

**Comment by YT-Advanced** [comment]
@s1204IT I have found a same problem from MustardChef repos (he is using same technology with our repos):
https://github.com/MustardChef/WSABuilds/issues/180

**Comment by s1204IT** [comment]
@YT-Advanced 
When built from our repository, there should be no missing files.

**Comment by s1204IT** [comment]
@rp1231
"**Build Issue number**" enter the issue number used to build, not the WSA version.

**Comment by baturcotte** [comment]
Problem still exists with the new 2309 build (WSA_2309.40000.200_x64_Release-Nightly-MindTheGapps-13.0-as-Pixel-5-RemovedAmazon.7z, downloaded 9/27/2023 15:08 PDT).

**Comment by s1204IT** [comment]
At least in my environment I can't reproduce it.

**Comment by YT-Advanced** [comment]
> Problem still exists with the new 2309 build (WSA_2309.40000.200_x64_Release-Nightly-MindTheGapps-13.0-as-Pixel-5-RemovedAmazon.7z, downloaded 9/27/2023 15:08 PDT).

How about Custom Build ?

**Comment by YT-Advanced** [comment]
> At least in my environment I can't reproduce it.

Mayeb your recent changes with pri not compatiable with Auto Merge lanaguage resource in Auto Build
