### ISSUE TITLE
[Documentation]userdata.vhdx may be named userdata.2.vhdx

### ISSUE THREAD

**Issue by BraINstinct0** [YT-Advanced/WSA-Script#574]
I do not know what exactly cause this, but I'm fairly sure there could be some duplication problems must've caused it.
Regardless, it is safe to assume it to be the userdata.vhdx when upgrading WSA, so an edit to show that `files starting with userdata and ends with vhdx` would suffice.

**Comment by BraINstinct0** [comment]
In that case, metadata.vhdx would also be renamed as metadata.2.vhdx - I'm not sure if this would interfere with the update procedure.

**Comment by YT-Advanced** [comment]
Microsoft sepearated the file, you can check it by clean install WSA

**Comment by BraINstinct0** [comment]
Hmm, so even if I don't se a userdata.vhdx there, there's no issue, right?

**Comment by YT-Advanced** [comment]
I think if you can run WSA normally, it is not a big issues
