### ISSUE TITLE
Modded WSA fail to start {Android 13} ver: 2307 400000

### ISSUE THREAD

**Issue by kevstar0** [YT-Advanced/WSA-Script#590]
### Steps to reproduce

1. Download modded wsa from [https://github.com/YT-Advanced/WSA-Script/releases/tag/v2023-09-03](url)
2. install WSA_2307.40000.6.0_x64_Release-Nightly-with-KernelSU-v0.6.7-MindTheGapps-13.0-as-Pixel-5-RemovedAmazon.7z
3. Allow WSA to update
4. log into google
5. reboot WSA

### Expected behaviour

1) Install should be successful
2) Expect a lot of reboots (Successful reboots are seen by google play protect notification popping out)
3) Google signin failed when logging in
4) After reboot google is signed in
5) Google sync activates (based on your account)
6) Sync will finish and WSA would need another reboot
7) WSA would fail to launch & hang on a bootloop until it gives up on it's own to boot (no google play protect notification would show up)

### Actual behaviour

WSA will fail to launch constantly trying to boot without any notification popping out like it normally does when booting up
[20230924132018.log](https://github.com/YT-Advanced/WSA-Script/files/12708700/20230924132018.log)

### Windows version

22621.2283

### Build Issue number

2307

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
@s1204IT Do u have any idea ?

**Comment by s1204IT** [comment]
I'll do a little verification.
So, please wait a moment.

**Comment by s1204IT** [comment]
@kevstar0 
If a bootloop occurs, please uninstall WSA and then reinstall it using "Rub.bat".
Also, please update your GMS and Play Store apps first before logging into your Google account.

**Comment by novaflame1** [comment]
I managed to get it installed, but nothing is actually launching, it shows me this 
![image](https://github.com/YT-Advanced/WSA-Script/assets/71691723/c194e3b6-6f09-4ef3-bee4-91c83ffaab96)
but doesn't fully load in, it closes out shortly afterwards, I do not know what to do to get it working.

**Comment by YT-Advanced** [comment]
Since no reply, I will close this issues

**Comment by s1204IT** [comment]
> @s1204IT Also I have read the logs and seem like GMS fail to start

This is because this is not the original installation method for MindTheGapps, so the setup cannot be done correctly.
This applies not only to virtual devices but also to real devices.
