### ISSUE TITLE
[Bug] Short description.

### ISSUE THREAD

**Issue by pony0996** [YT-Advanced/WSA-Script#622]
### Steps to reproduce

1. 'run.bat' running error
2. SHA-256 value is correct
3. WSA_2309.40000.2.0_x64_Release-Nightly-with-Magisk-26.3-stable-MindTheGapps-13.0-as-Pixel-5-RemovedAmazon

### Expected behaviour

1

### Actual behaviour

[](url)
![屏幕截图 2023-09-29 162138](https://github.com/YT-Advanced/WSA-Script/assets/100555625/e0f7a727-47de-4789-87c4-0dbab7a7f24e)

### Windows version

win 11

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
@pony0996 First, send me the `filelist.txt` in your extracted folder, and also check if you have `priinfo` folder in your directory
