### ISSUE TITLE
Custom WSA Build [Test]

### ISSUE THREAD

**Issue by s1204IT** [YT-Advanced/WSA-Script#654]
--arch x64 --release-type latest --magisk-ver canary --gapps-brand MindTheGapps --root-sol magisk --custom-model redfin --compress-format 7z --remove-amazon

**Comment by YT-Advanced** [comment]
@s1204IT Make pri worked, but can you check the compact image too ? Just need to download and compare image size before and after run install.ps1

**Comment by s1204IT** [comment]
> @s1204IT Make pri worked, but can you check the compact image too ? Just need to download and compare image size before and after run install.ps1

Yes, at least "Compact Images" is working.
This was verified in the previous PR.

**Comment by YT-Advanced** [comment]
> > @s1204IT Make pri worked, but can you check the compact image too ? Just need to download and compare image size before and after run install.ps1
> 
> Yes, at least "Compact Images" is working. This was verified in the previous PR.

The image size is smaller with Compact Images, right ?
