### ISSUE TITLE
[Bug] installs but does not launch, been waiting all day

### ISSUE THREAD

**Issue by Plaguewave7** [YT-Advanced/WSA-Script#660]
### Steps to reproduce

1. install WSA_2307.40000.6.0_x64_Release-Nightly-with-Magisk-26.1-stable-MindTheGapps-13.0-as-Pixel-5-RemovedAmazon
2. extract zip file
3. click on run.bat
4. let it install
5. press any button to close powershell
6. wait for WSA to load and open

### Expected behaviour

what should happen is this
1. WSA boots up and starts setting everything up. (should reboot several times, getting the Google play protect notification is a sign of reboot)
2. update WSA
3. sign into google
4. should fail to sign in then reboot with you signed in
5. sync will finish according to your account
6. WSA will fail to launch and start in a boot loop till it gives up on it's own (no google play protect notification will show up)

### Actual behaviour

google play starts the boot up process, but then eventually gives up before giving me the chance to sign into google account. 

### Windows version

22621.1992

### Build Issue number

2307

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by novaflame1** [comment]
> We are checking your Issues body and head ...
> 
> > https://github.com/YT-Advanced/WSA-Script/actions/runs/6400095650

thank you, let me know if you fix the issue, I would greatly appreciate it.

**Comment by YT-Advanced** [comment]
> > We are checking your Issues body and head ...
> > 
> > > https://github.com/YT-Advanced/WSA-Script/actions/runs/6400095650
> 
> thank you, let me know if you fix the issue, I would greatly appreciate it.

Lol, it is bot comment. But can u check biild in WSA-Insider-Build too ?

**Comment by novaflame1** [comment]
> > > We are checking your Issues body and head ...
> > > > https://github.com/YT-Advanced/WSA-Script/actions/runs/6400095650
> > 
> > 
> > thank you, let me know if you fix the issue, I would greatly appreciate it.
> 
> Lol, it is bot comment. But can u check biild in WSA-Insider-Build too ?

ah, pardon me, but thanks none the less, I didn't check what I was replying to till after I posted, had a bit of a brainfart moment.

**Comment by Plaguewave7** [comment]
> > > We are checking your Issues body and head ...
> > > > https://github.com/YT-Advanced/WSA-Script/actions/runs/6400095650
> > 
> > 
> > thank you, let me know if you fix the issue, I would greatly appreciate it.
> 
> Lol, it is bot comment. But can u check biild in WSA-Insider-Build too ?

that actually installed, thanks
