### ISSUE TITLE
[Bug] Getting an error in magisk

### ISSUE THREAD

**Issue by rp1231** [YT-Advanced/WSA-Script#689]
### Steps to reproduce

1. Download the [WSA_2308.40000.3.0_x64_Release-Nightly-with-Magisk-26.3-stable-MindTheGapps-13.0-as-Pixel-5-RemovedAmazon.7z](https://github.com/YT-Advanced/WSA-Script/releases/download/v2023-10-03/WSA_2308.40000.3.0_x64_Release-Nightly-with-Magisk-26.3-stable-MindTheGapps-13.0-as-Pixel-5-RemovedAmazon.7z)
2. Run the run.bat file

### Expected behaviour

The magisk window pops up with no error

### Actual behaviour

Magisk window pops up with this error:
<img width="960" alt="WsaClient_lUOG1z5b7f" src="https://github.com/YT-Advanced/WSA-Script/assets/47380919/3f9c2174-8612-4a5e-8639-935228731d3e">

### Windows version

Version 22H2 (0S Build 22621.2361)

### Build Issue number

Am downloading the builds from the release section, am not building it myself.

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
Hi, can you check our latest build
