### ISSUE TITLE
[Bug] Few files in latest insider version report compression error

### ISSUE THREAD

**Issue by Saud-97** [YT-Advanced/WSA-Script#740]
### Steps to reproduce

1.  Download [WSA_2309.40000.8.0_x64_Release-Nightly-with-Magisk-26.3-stable-MindTheGapps-13.0-as-Pixel-5-RemovedAmazon.7z](https://github.com/YT-Advanced/WSA-Script/releases/download/WSA-Insider-Version/WSA_2309.40000.8.0_x64_Release-Nightly-with-Magisk-26.3-stable-MindTheGapps-13.0-as-Pixel-5-RemovedAmazon.7z)
2. Decompress using WinRAR

### Expected behaviour

Decompressed normally

### Actual behaviour

Error:

![image](https://github.com/YT-Advanced/WSA-Script/assets/39028181/9277cc66-e9d8-488e-bd88-0b6d0d983835)

I tried another way using default windows app.
![image](https://github.com/YT-Advanced/WSA-Script/assets/39028181/9e29a209-d9dc-4c29-a57d-efe66665f367)

I was able to extract without errors using 7z, but I think its better to fix this for other users. The version before this one wasn't causing any issues with WinRAR.

### Windows version

11

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by Saud-97** [comment]
Might be related to https://github.com/YT-Advanced/WSA-Script/pull/721

**Comment by YT-Advanced** [comment]
Have you updated the Winrar to latest ?

**Comment by Saud-97** [comment]
> Have you updated the Winrar to latest ?

No, it worked after I updated it. Thank you. 

Nevertheless,  I think its better to not adapt very new technologies until it becomes standard and mature.
