### ISSUE TITLE
[Restriction] VPN does not work.

### ISSUE THREAD

**Issue by s1204IT** [YT-Advanced/WSA-Script#77]
As long as it is completely restricted on the WSA side, I don't see the need to bother rewriting VpnDialogs.

--- 
My suggestion: Remove customized `VpnDialogs`.

@YT-Advanced Please reply back whether you **agree** or **disagree** with this.

If agree, I'll get right to work.

**Comment by YT-Advanced** [comment]
@s1204IT So when removed VPNDialogs, does the VPN work ?

**Comment by s1204IT** [comment]
In the first place, VPN is disallowed by System restriction, so it cannot be used anyway.

If it is not available, then the original application should be used.
It is not practical to use a VPN with the current WSA.

**Comment by YT-Advanced** [comment]
@s1204IT I think sometime we need to use VPN in WSA

**Comment by s1204IT** [comment]
> @s1204IT I think sometime we need to use VPN in WSA. So if you can, please keep it

The fundamental problem is that it is useless to replace an application without it working as it should.
It can be easily restored at any time and will be deleted this time.
We will attempt to restore it when we make progress on LSPosed.
