### ISSUE TITLE
[Feature Request] Attach an updater script

### ISSUE THREAD

**Issue by Saud-97** [YT-Advanced/WSA-Script#782]
### Is your feature request related to a problem?

Hello, can you attach an updater that notifies you about a new version upon opening WSA?

### Describe the solution you'd like

Hopefully it can download and unpack the update to the WSA directory. The updater must be configurable to allow to skip certain updates and let you know about release notes if any. Also it can be disabled if user didn't want to update. And can update manually.

An even better solution is to implement it as an optional APK that handles that but I know it might be an overkill so a normal script or scheduled task might be easier and more manageable.

### Additional context

Something similar to this github update checker.

https://github.com/Saud-97/TachiyomiS97/blob/2c993e8e659568d701fe320a64c07fd02bfef8df/app/src/main/java/eu/kanade/tachiyomi/data/updater/AppUpdateChecker.kt#L59

**Comment by Saud-97** [comment]
delete builds

**Comment by YT-Advanced** [comment]
This is great idea. But I think user should download and install by themselves because sometimes, Microsoft make WSA unpatchable or WSA may not worked probally with Magisk and GApps

**Comment by Saud-97** [comment]
> This is great idea. But I think user should download and install by themselves because sometimes, Microsoft make WSA unpatchable or WSA may not worked probally with Magisk and GApps

But this won't have any effect on updater as its essentially the same as the normal update process that you added in the readme. 

Perhaps if a certain update needs manual interference you may edit the Run.bat to ignore being ran from the updater process or may add a certain flag that indicates this is an updater call for example `Run.bat -update` and reject the execution based on a logic.

A back up and restore method attached to the updater may come in handy if there were any issues or exception to return back to the old state and restore.

**Comment by Saud-97** [comment]
For notifications purpose GitHub already does that when you enable watch repo function and it will notify on releases.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by s1204IT** [comment]
What I think is that instead of directly updating the WSA files, it will only notify you when there is an update to the WSA.
However, this only works when the user runs the script, so I'm thinking of embedding it in a system app and notifying it via WSA.

The reason why WSA does not or cannot update directly is because the Magisk version and model name may be different.

**Comment by s1204IT** [comment]
At this point, there are no more updates to WSA itself, so we will end this discussion.

Magisk and KernelSU can be checked against each other from the app.
