### ISSUE TITLE
[Bug] Multiple problems

### ISSUE THREAD

**Issue by dennbenn73** [YT-Advanced/WSA-Script#803]
### Steps to reproduce

1. Downloaded and checked file integrity of prebuilt asset WSA_2309.40000.10.0_x64_Release-Nightly-MindTheGapps-13.0-as-Pixel-5-RemovedAmazon.7z 
2.  Extracted archive to folder on C:\ of Surface Pro 9 (Core i7-1265U, 16GB RAM) 
3.  Executed `Run.bat` but was not prompted with request for WSA administrative permission
4.  Opened Terminal (Admin) and executed `PowerShell.exe -ExecutionPolicy Bypass -File .\Install.ps1` command

### Expected behaviour

Executing `Run.bat` and/or `Install.ps1` files should install prebuilt WSA as described by the instruction guide.

### Actual behaviour

1. Gapps was not installed.
2. Subsystem resources are locked on 'Partially running' setting - cannot be adjusted to 'As needed' or 'Continuous' settings.
3. Attempting to open WSA 'Manage developer settings' causes subsystem force close with permission error message: "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item."
![permission_error](https://github.com/YT-Advanced/WSA-Script/assets/59033886/aacef992-717b-42e6-8ef4-f1d7c444b8d8)

### Windows version

11.0.22621.2506 (22H2)

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
First, uninstall your installed build, then delete the extracted folder.
Next, extract again but with a short folder name, example: "WSA"
Install again and check back

**Comment by dennbenn73** [comment]
There wasn't any request for Admin privilege during the either installation attempt. I have shortened the folder name, and was given the same error message.
![permission_error](https://github.com/YT-Advanced/WSA-Script/assets/59033886/1654a940-33a8-445f-8d24-7858479edb92)

I had the official WSA installed before; how do I know if the previous installation has been completely removed?

**Comment by YT-Advanced** [comment]
You can check if WSA still shown in Settings or Control Panel. And also go to this path and delete it `%LOCALAPPDATA%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe`

**Comment by dennbenn73** [comment]
I think I am looking in the correct location `C:\Users\denn_\AppData\Local\Packages\` and I didn't see any folder named `MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe` 

Windows 11 is a permissions nightmare.

**Comment by s1204IT** [comment]
Please install the latest version.
