### ISSUE TITLE
[Bug] Extraction failed.

### ISSUE THREAD

**Issue by a0533057932** [YT-Advanced/WSA-Script#819]
### Steps to reproduce

WSA release extraction

### Expected behaviour

Successful rescue

### Actual behaviour

Extraction failed due to 4 files

שיטה בלתי נתמכת של דחיסה : WSACrashUploader\arm64\KernelTraceControl.dll
שיטה בלתי נתמכת של דחיסה : WSACrashUploader\arm64\msdia140.dll
שיטה בלתי נתמכת של דחיסה : WSACrashUploader\arm64\msvcp140.dll
שיטה בלתי נתמכת של דחיסה : WSACrashUploader\arm64\vcruntime140.dll

### Windows version

22621.2506

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by a0533057932** [comment]
Manual creation of the WSA without compression for Z7 works properly
Only the compression to Z7 causes a problem

**Comment by a0533057932** [comment]
https://github.com/YT-Advanced/WSA-Script/actions/runs/6709262512
The file here is correct
Unlike the file in the releases section

**Comment by a0533057932** [comment]
Manually building 7Z brings the same error
https://github.com/a0533057932/test-WSA-Script/actions/runs/6710802278
Compared to building according to the exact same parameters only of ZIP that will be installed
https://github.com/a0533057932/test-WSA-Script/actions/runs/6709942104

Even such a construction
WSA_2309.40000.10.0_x64_Release-Nightly-NoGApps-RemovedAmazon-compressed
you failed

https://github.com/a0533057932/test-WSA-Script/actions/runs/6711004759

**Comment by YT-Advanced** [comment]
@a0533057932 Updatr your WinRar or 7ZIP to latest version

**Comment by a0533057932** [comment]
> @a0533057932עדכן את WinRar או 7ZIP שלך לגרסה האחרונה

right
I updated 7Z and now it works fine
Such a simple solution I just didn't think to check it
