### ISSUE TITLE
wsasettings.winmd cannot be unpacked!

### ISSUE THREAD

**Issue by RdBwai** [YT-Advanced/WSA-Script#841]
### Steps to reproduce

1. After I tried to overwrite the previous version 2308.40000.4.0 with the new version 2309.40000.10.0, I get the message wsasettings.winmd cannot be unpacked at about 97%!
2.  When I turn off the message, certain files are not copied to the WSA folder from which I have always successfully upgraded newer versions of WSA - until now.
3. 

### Expected behaviour

All files should be normally copied.

### Actual behaviour

Only part of al files are copied - with message: wsasettings.winmd cannot be unpacked!

### Windows version

Windows 11 Insider Preview 10.0.22635.2419 (ni_release)

### Build Issue number

#1

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
Do you have any screenshot

**Comment by RdBwai** [comment]
Here ...
![WSsaSettings](https://github.com/YT-Advanced/WSA-Script/assets/112920978/8eac6430-4af8-4976-b41b-f5d53e40b02f)

**Comment by Klbgr** [comment]
I got a similar problem using 7zip and fixed it by installing latest version of it.

**Comment by RdBwai** [comment]
> I got a similar problem using 7zip and fixed it by installing latest version of it.

Thanks for your tip. Till now I was always unziping downloaded MagiskonWSA with internal unziper from Total Commander. Now I try with File Explorere and it works without problem. After that installation went fine and everything is working now - thanks again!
