### ISSUE TITLE
[Bug] Short description.

### ISSUE THREAD

**Issue by Plaguewave7** [YT-Advanced/WSA-Script#871]
### Steps to reproduce

1. download WSA-Script
2. extract WSA-Script into WSA folder

### Expected behaviour

Extracts successfully into folder

### Actual behaviour

Extracts with errors when extracting WSACrashUploader claiming that the volume is corrupted

### Windows version

22H2

### Build Issue number

2310

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by adamrubock** [comment]
This is what it looks like in NanaZip.

![Screenshot 2023-11-12 153659](https://github.com/YT-Advanced/WSA-Script/assets/7032854/0506a33e-eb52-407c-bfe7-6770de5f293f)

When I use the built-in archive tool in Windows Explorer, it says "Catastrophic Error."

However, if I remove these lines in `filelist.txt`, it goes through just fine:

![Screenshot 2023-11-12 165902](https://github.com/YT-Advanced/WSA-Script/assets/7032854/1decbdb8-7e05-4c0d-b917-50d6106a7b0d)

**Comment by s1204IT** [comment]
Please try with [**7-Zip**](https://www.7-zip.org/download.html "Download 7-Zip").
