### ISSUE TITLE
[Feature Request] VHDX conversion-only script (VHDX to IMG to VHDX)

### ISSUE THREAD

**Issue by jsm0372** [YT-Advanced/WSA-Script#899]
### Is your feature request related to a problem?

Would it be possible to document the scripted actions that need to take place in order to convert the VHDX to IMG and back to VHDX? I found the relevant code within build.sh that I can try manually but am afraid I might miss some other necessary logic within your build.sh script. I'm trying to build my own WSA based on the WSAGAScript instructions, which obviously fail at the point of dealing with the IMG files.

### Describe the solution you'd like

Document or provide the script logic for only converting the VHDX to IMG and back to VHDX.

**Comment by YT-Advanced** [comment]
Can u explain more pls ?

**Comment by jsm0372** [comment]
I'm requesting if it would be possible to provide a single script to only convert the VHDX files to IMG files. If it's a simple matter of using QEMU then I can do that, just wasn't sure if there were other tasks required to make the conversion successful.

**Comment by YT-Advanced** [comment]
Now in WSA, we have 2 types of image is EROFS and EXT4. You can check build.sh file for easier understanding
For EXT4:
1. Convert VHDX to raw image using QEMU
2. Remove read-only flag (`ro_ext4_img_to_rw` class)
3. Caculate required image size and resize image
4. Mount image
5. Unmount and shrink image
6. Convert back to VHDX image
And for EROFS image is:
1. Convert VHDX to raw image using QEMU
2. Mount image
3. Create overlayfs and make overlayfs to make the image writeable (`mk_overlayfs` class)
4. Apply changes
5. Use `erofs-utils` for creating new EROFS image (`mk_erofs_umount` class)
7. Convert back to VHDX using qemu
