### ISSUE TITLE
[Bug] Redundant portion of Custom Builder

### ISSUE THREAD

**Issue by robbely** [YT-Advanced/WSA-Script#970]
### Steps to reproduce

(build with no root solution)

### Expected behaviour

The custom builder script asks for "Magisk version" even if "Root solution" is set to "None". If I remove the command line switch for magisk version, there is a build error.

With root solution set to none (or different root solution), what does this switch do, and why does removing it giver an error when magisk isnt being used? Also will magisk still be there in some form in my custom build?

### Actual behaviour

(build error when switch removed)

### Windows version

10.0.19045.3693

### Build Issue number

#968

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment]
You don't need to care about this, because my script will not apply root
